permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build 🔧
        run: |
          npm run generate

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: .output/public
